export const stepLabels = ['A', 'B', 'C', 'D', 'E']
export const stepIndivatorStyles = {
  stepIndicatorSize: 20,
  currentStepIndicatorSize: 20,
  separatorStrokeWidth: 3,
  stepStrokeWidth: 3,
  currentStepStrokeWidth: 3,
  stepStrokeCurrentColor: '#d70000',
  stepStrokeFinishedColor: '#ccc',
  stepStrokeUnFinishedColor: '#ccc',
  separatorFinishedColor: '#ccc',
  separatorUnFinishedColor: '#ccc',
  stepIndicatorFinishedColor: '#ccc',
  stepIndicatorUnFinishedColor: '#ccc',
  stepIndicatorCurrentColor: '#d70000',
  stepIndicatorLabelFontSize: 0,
  currentStepIndicatorLabelFontSize: 0,
  stepIndicatorLabelCurrentColor: '#d70000',
  stepIndicatorLabelFinishedColor: '#ccc',
  stepIndicatorLabelUnFinishedColor: '#ccc',
  labelColor: '#666',
  currentStepLabelColor: '#333',
  labelSize: 14,
}
