export const stepLabels = ['A', 'B', 'C', 'D', 'E']
export const stepIndivatorStyles = {
  stepIndicatorSize: 14,
  currentStepIndicatorSize: 14,
  separatorStrokeWidth: 1.5,
  stepStrokeWidth: 1.5,
  currentStepStrokeWidth: 1.5,
  stepStrokeCurrentColor: '#d70000',
  stepStrokeFinishedColor: '#ccc',
  stepStrokeUnFinishedColor: '#ccc',
  separatorFinishedColor: '#ccc',
  separatorUnFinishedColor: '#ccc',
  stepIndicatorFinishedColor: '#ccc',
  stepIndicatorUnFinishedColor: '#ccc',
  stepIndicatorCurrentColor: '#d70000',
  stepIndicatorLabelFontSize: 1,
  currentStepIndicatorLabelFontSize: 1,
  stepIndicatorLabelCurrentColor: '#d70000',
  stepIndicatorLabelFinishedColor: '#ccc',
  stepIndicatorLabelUnFinishedColor: '#ccc',
  labelColor: '#666',
  currentStepLabelColor: '#333',
  labelSize: 10,
}
