export const stepLabels = ['サンプルA', 'サンプルB', 'サンプルC']
export const stepIndivatorStyles = {
  stepIndicatorSize: 35,
  currentStepIndicatorSize:40,
  separatorStrokeWidth: 3,
  stepStrokeWidth: 3,
  currentStepStrokeWidth: 3,
  stepStrokeCurrentColor: '#d70000',
  stepStrokeFinishedColor: '#d70000',
  stepStrokeUnFinishedColor: '#ccc',
  separatorFinishedColor: '#d70000',
  separatorUnFinishedColor: '#ccc',
  stepIndicatorFinishedColor: '#d70000',
  stepIndicatorUnFinishedColor: '#fff',
  stepIndicatorCurrentColor: '#fff',
  stepIndicatorLabelFontSize: 14,
  currentStepIndicatorLabelFontSize: 14,
  stepIndicatorLabelCurrentColor: '#333',
  stepIndicatorLabelFinishedColor: '#fff',
  stepIndicatorLabelUnFinishedColor: '#333',
  labelColor: '#333',
  currentStepLabelColor: '#333',
  labelSize: 14,
}